### ISSUE TITLE
Question about plugin

### ISSUE THREAD

**Issue by rlee1990** [florent-huran/sumup-flutter#2]
Is this plugin androidx integrated? Also is this still being maintained

**Comment by florent-huran** [comment]
In my memory it isn't android integrated.

As another of my personal projects will need this flutter implementation in future months, I'll be more active on this one.

**Comment by rlee1990** [comment]
Okay I did see they do have android and iOS sdks. I also have an upcoming project that uses sumup ill try to make a pull request and see if I can help out at all. It’s better then me starting from scratch. Thanks for the quick reply @florent-huran

**Comment by florent-huran** [comment]
Yes this repo is calling native SDKs, so if you want to migrate to AndroidX basically you'd just have to open the android folder in Android Studio, then use the automatic migration to AndroidX.
As it is a really small project the automatic migration does a really good job in general.

As I'm an iOS developer, I just sticked to the official documentation without tempting anything else on Android.
However, I'd love to help to improve this library too, and as my project is becoming closer each day it's just a matter of time :)

**Comment by rlee1990** [comment]
Okay thanks I’ll try that later today and let you know how it goes
